// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqfwfhxyxjbqldpeaqgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxZndmaHh5eGpicWxkcGVhcWd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzkwMzYsImV4cCI6MjA1OTk1NTAzNn0.HBRakBVld5yyfjjCaddesRnwHQz_oJfRAW7QbKZ5ib0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);